date = input("enter your birthday date: ")
print("My birthday date is:", date)

date2 = input("enter your birthday date: ")
print("My birthday date is:", date2)

date3 = input("enter your birthday date: ")
print("My birthday date is:", date3)

date4 = input("enter your birthday date: ")
print("My birthday date is:", date4)

date5 = input("enter your birthday date: ")
print("My birthday date is:", date5)